UNWIND [
  {id: 1, name: 'Java'},
  {id: 2, name: 'Spring Boot'},
  {id: 3, name: 'PostgreSQL'},
  {id: 4, name: 'MongoDB'},
  {id: 5, name: 'Kafka'},
  {id: 6, name: 'Redis'},
  {id: 7, name: 'Docker'},
  {id: 8, name: 'Kubernetes'},
  {id: 9, name: 'AWS'},
  {id: 10, name: 'React'},
  {id: 11, name: 'Angular'},
  {id: 12, name: 'TypeScript'},
  {id: 13, name: 'Node.js'},
  {id: 14, name: 'Python'},
  {id: 15, name: 'Machine Learning'},
  {id: 16, name: 'SQL'},
  {id: 17, name: 'Microservices'},
  {id: 18, name: 'REST API'},
  {id: 19, name: 'GraphQL'},
  {id: 20, name: 'Neo4j'},
  {id: 21, name: 'Hibernate'},
  {id: 22, name: 'Git'},
  {id: 23, name: 'CI/CD'},
  {id: 24, name: 'Terraform'},
  {id: 25, name: 'Linux'},
  {id: 26, name: 'Pandas'},
  {id: 27, name: 'Spark'},
  {id: 28, name: 'Next.js'},
  {id: 29, name: 'Go'},
  {id: 30, name: 'Elasticsearch'},
  {id: 31, name: 'System Design'},
  {id: 32, name: 'Data Structures'},
  {id: 33, name: 'RabbitMQ'},
  {id: 34, name: 'Azure'},
  {id: 35, name: 'GCP'},
  {id: 36, name: 'Vue.js'},
  {id: 37, name: 'Django'},
  {id: 38, name: 'FastAPI'},
  {id: 39, name: 'Airflow'},
  {id: 40, name: 'TensorFlow'}
] AS row
MERGE (s:Skill {id: row.id})
SET s.name = row.name;
