UNWIND [
  {id: 1, title: 'Java Backend Developer', location: 'Bengaluru', minExperienceYears: 4, salary: 1800000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [1, 2, 3, 18]},
  {id: 2, title: 'Senior Spring Boot Engineer', location: 'Bengaluru', minExperienceYears: 6, salary: 2600000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [1, 2, 17, 5, 21]},
  {id: 3, title: 'Backend Developer', location: 'Hyderabad', minExperienceYears: 3, salary: 1600000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [1, 2, 3, 7]},
  {id: 4, title: 'Microservices Architect', location: 'Bengaluru', minExperienceYears: 8, salary: 3500000, employmentType: 'FULL_TIME', companyId: 12, skillIds: [1, 2, 17, 5, 31]},
  {id: 5, title: 'Full Stack Java Developer', location: 'Mumbai', minExperienceYears: 5, salary: 2100000, employmentType: 'FULL_TIME', companyId: 4, skillIds: [1, 2, 10, 12]},
  {id: 6, title: 'React Frontend Engineer', location: 'Pune', minExperienceYears: 2, salary: 1400000, employmentType: 'FULL_TIME', companyId: 2, skillIds: [10, 12, 28, 18]},
  {id: 7, title: 'Senior Frontend Engineer', location: 'Bengaluru', minExperienceYears: 5, salary: 2400000, employmentType: 'FULL_TIME', companyId: 9, skillIds: [10, 12, 19, 28]},
  {id: 8, title: 'Angular Developer', location: 'Chennai', minExperienceYears: 3, salary: 1300000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [11, 12, 18]},
  {id: 9, title: 'Node.js Developer', location: 'Remote', minExperienceYears: 2, salary: 1500000, employmentType: 'FULL_TIME', companyId: 10, skillIds: [13, 12, 4, 18]},
  {id: 10, title: 'Python ML Engineer', location: 'Hyderabad', minExperienceYears: 3, salary: 2000000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [14, 15, 26, 16]},
  {id: 11, title: 'Machine Learning Scientist', location: 'Bengaluru', minExperienceYears: 5, salary: 3200000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [14, 15, 26, 27]},
  {id: 12, title: 'Data Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2200000, employmentType: 'FULL_TIME', companyId: 8, skillIds: [14, 16, 27, 5, 9]},
  {id: 13, title: 'DevOps Engineer', location: 'Delhi', minExperienceYears: 4, salary: 1900000, employmentType: 'FULL_TIME', companyId: 3, skillIds: [7, 8, 9, 23, 25]},
  {id: 14, title: 'SRE', location: 'Bengaluru', minExperienceYears: 6, salary: 2800000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [8, 9, 24, 25, 23]},
  {id: 15, title: 'Cloud Engineer', location: 'Hyderabad', minExperienceYears: 3, salary: 1800000, employmentType: 'FULL_TIME', companyId: 7, skillIds: [9, 7, 24, 23]},
  {id: 16, title: 'Platform Engineer', location: 'Remote', minExperienceYears: 5, salary: 2500000, employmentType: 'FULL_TIME', companyId: 7, skillIds: [8, 9, 7, 23, 1]},
  {id: 17, title: 'Go Backend Engineer', location: 'Chennai', minExperienceYears: 2, salary: 1600000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [29, 7, 3, 18]},
  {id: 18, title: 'Graph Database Engineer', location: 'Pune', minExperienceYears: 4, salary: 2100000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [1, 2, 20, 3]},
  {id: 19, title: 'Java Engineer', location: 'Pune', minExperienceYears: 3, salary: 1500000, employmentType: 'FULL_TIME', companyId: 2, skillIds: [1, 2, 21, 3]},
  {id: 20, title: 'Senior Java Developer', location: 'Delhi', minExperienceYears: 6, salary: 2300000, employmentType: 'FULL_TIME', companyId: 3, skillIds: [1, 2, 17, 18]},
  {id: 21, title: 'Payments Backend Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2400000, employmentType: 'FULL_TIME', companyId: 10, skillIds: [1, 2, 5, 6, 3]},
  {id: 22, title: 'Fintech Java Developer', location: 'Bengaluru', minExperienceYears: 5, salary: 2600000, employmentType: 'FULL_TIME', companyId: 12, skillIds: [1, 2, 5, 17]},
  {id: 23, title: 'Kafka Streaming Engineer', location: 'Hyderabad', minExperienceYears: 5, salary: 2400000, employmentType: 'FULL_TIME', companyId: 8, skillIds: [5, 1, 6, 17]},
  {id: 24, title: 'Search Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2200000, employmentType: 'FULL_TIME', companyId: 9, skillIds: [30, 1, 7, 16]},
  {id: 25, title: 'UI Engineer', location: 'Mumbai', minExperienceYears: 2, salary: 1200000, employmentType: 'FULL_TIME', companyId: 4, skillIds: [10, 12, 18]},
  {id: 26, title: 'Next.js Developer', location: 'Remote', minExperienceYears: 1, salary: 1100000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [28, 10, 12]},
  {id: 27, title: 'Intern - Backend', location: 'Bengaluru', minExperienceYears: 0, salary: 400000, employmentType: 'INTERNSHIP', companyId: 11, skillIds: [1, 18, 22]},
  {id: 28, title: 'Contract Spring Developer', location: 'Remote', minExperienceYears: 4, salary: 2000000, employmentType: 'CONTRACT', companyId: 4, skillIds: [1, 2, 18]},
  {id: 29, title: 'Data Scientist', location: 'Mumbai', minExperienceYears: 4, salary: 2300000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [14, 15, 26, 16]},
  {id: 30, title: 'Analytics Engineer', location: 'Pune', minExperienceYears: 3, salary: 1700000, employmentType: 'FULL_TIME', companyId: 2, skillIds: [14, 16, 26]},
  {id: 31, title: 'Staff Backend Engineer', location: 'Bengaluru', minExperienceYears: 9, salary: 4200000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [1, 17, 31, 5, 8]},
  {id: 32, title: 'Principal Java Architect', location: 'Bengaluru', minExperienceYears: 10, salary: 5000000, employmentType: 'FULL_TIME', companyId: 7, skillIds: [1, 2, 17, 31, 9]},
  {id: 33, title: 'Web Engineer', location: 'Chennai', minExperienceYears: 3, salary: 1500000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [10, 12, 13]},
  {id: 34, title: 'AWS DevOps Specialist', location: 'Delhi', minExperienceYears: 5, salary: 2100000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [9, 7, 8, 23]},
  {id: 35, title: 'Kubernetes Engineer', location: 'Hyderabad', minExperienceYears: 4, salary: 2000000, employmentType: 'FULL_TIME', companyId: 3, skillIds: [8, 7, 23, 25]},
  {id: 36, title: 'SQL Developer', location: 'Pune', minExperienceYears: 2, salary: 1000000, employmentType: 'FULL_TIME', companyId: 2, skillIds: [16, 3, 18]},
  {id: 37, title: 'Hibernate/JPA Developer', location: 'Chennai', minExperienceYears: 3, salary: 1400000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [1, 21, 3, 2]},
  {id: 38, title: 'Redis Cache Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 1900000, employmentType: 'FULL_TIME', companyId: 12, skillIds: [6, 1, 2, 17]},
  {id: 39, title: 'GraphQL API Engineer', location: 'Mumbai', minExperienceYears: 3, salary: 1700000, employmentType: 'FULL_TIME', companyId: 9, skillIds: [19, 13, 12, 18]},
  {id: 40, title: 'CI/CD Engineer', location: 'Remote', minExperienceYears: 4, salary: 1800000, employmentType: 'FULL_TIME', companyId: 4, skillIds: [23, 7, 22, 9]},
  {id: 41, title: 'Linux Systems Engineer', location: 'Delhi', minExperienceYears: 3, salary: 1400000, employmentType: 'FULL_TIME', companyId: 3, skillIds: [25, 7, 22]},
  {id: 42, title: 'Spark Data Engineer', location: 'Hyderabad', minExperienceYears: 5, salary: 2500000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [27, 14, 16, 9]},
  {id: 43, title: 'Product Backend Engineer', location: 'Bengaluru', minExperienceYears: 3, salary: 2000000, employmentType: 'FULL_TIME', companyId: 9, skillIds: [1, 2, 18, 7]},
  {id: 44, title: 'Junior Java Developer', location: 'Hyderabad', minExperienceYears: 1, salary: 900000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [1, 18, 22, 32]},
  {id: 45, title: 'Senior React Engineer', location: 'Pune', minExperienceYears: 5, salary: 2200000, employmentType: 'FULL_TIME', companyId: 8, skillIds: [10, 12, 28, 19]},
  {id: 46, title: 'Terraform Engineer', location: 'Remote', minExperienceYears: 4, salary: 2100000, employmentType: 'CONTRACT', companyId: 7, skillIds: [24, 9, 8, 23]},
  {id: 47, title: 'MongoDB Developer', location: 'Chennai', minExperienceYears: 2, salary: 1300000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [4, 13, 18]},
  {id: 48, title: 'System Design Mentor', location: 'Bengaluru', minExperienceYears: 8, salary: 3000000, employmentType: 'CONTRACT', companyId: 6, skillIds: [31, 1, 17, 32]},
  {id: 49, title: 'Infosys Java Consultant', location: 'Bengaluru', minExperienceYears: 5, salary: 1700000, employmentType: 'FULL_TIME', companyId: 1, skillIds: [1, 2, 21, 17]},
  {id: 50, title: 'PhonePe Backend Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2700000, employmentType: 'FULL_TIME', companyId: 12, skillIds: [1, 2, 5, 6, 31]},
  {id: 51, title: 'RabbitMQ Messaging Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2100000, employmentType: 'FULL_TIME', companyId: 14, skillIds: [33, 1, 5, 17]},
  {id: 52, title: 'Azure Cloud Engineer', location: 'Delhi', minExperienceYears: 4, salary: 2000000, employmentType: 'FULL_TIME', companyId: 16, skillIds: [34, 7, 8, 23]},
  {id: 53, title: 'GCP Data Engineer', location: 'Hyderabad', minExperienceYears: 5, salary: 2400000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [35, 14, 27, 39]},
  {id: 54, title: 'Vue.js Frontend Engineer', location: 'Pune', minExperienceYears: 3, salary: 1500000, employmentType: 'FULL_TIME', companyId: 13, skillIds: [36, 12, 10, 18]},
  {id: 55, title: 'Django Developer', location: 'Chennai', minExperienceYears: 2, salary: 1400000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [37, 14, 3, 18]},
  {id: 56, title: 'FastAPI Engineer', location: 'Remote', minExperienceYears: 3, salary: 1800000, employmentType: 'FULL_TIME', companyId: 13, skillIds: [38, 14, 18, 4]},
  {id: 57, title: 'Airflow Data Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2300000, employmentType: 'FULL_TIME', companyId: 8, skillIds: [39, 14, 16, 9]},
  {id: 58, title: 'Deep Learning Engineer', location: 'Bengaluru', minExperienceYears: 4, salary: 2800000, employmentType: 'FULL_TIME', companyId: 6, skillIds: [40, 15, 14, 26]},
  {id: 59, title: 'Paytm Backend Engineer', location: 'Noida', minExperienceYears: 4, salary: 2200000, employmentType: 'FULL_TIME', companyId: 14, skillIds: [1, 2, 5, 6]},
  {id: 60, title: 'Freshworks Full Stack Engineer', location: 'Chennai', minExperienceYears: 3, salary: 1800000, employmentType: 'FULL_TIME', companyId: 13, skillIds: [10, 13, 12, 18]},
  {id: 61, title: 'IBM Java Consultant', location: 'Bengaluru', minExperienceYears: 6, salary: 2000000, employmentType: 'FULL_TIME', companyId: 16, skillIds: [1, 2, 21, 17]},
  {id: 62, title: 'Cognizant Spring Developer', location: 'Pune', minExperienceYears: 3, salary: 1400000, employmentType: 'FULL_TIME', companyId: 15, skillIds: [1, 2, 18, 3]},
  {id: 63, title: 'Razorpay Platform Engineer', location: 'Bengaluru', minExperienceYears: 5, salary: 2600000, employmentType: 'FULL_TIME', companyId: 10, skillIds: [1, 8, 5, 31]},
  {id: 64, title: 'Swiggy Data Analyst Engineer', location: 'Bengaluru', minExperienceYears: 2, salary: 1600000, employmentType: 'FULL_TIME', companyId: 9, skillIds: [14, 16, 26, 3]},
  {id: 65, title: 'Microsoft SRE', location: 'Hyderabad', minExperienceYears: 5, salary: 3000000, employmentType: 'FULL_TIME', companyId: 7, skillIds: [8, 9, 25, 23, 24]},
  {id: 66, title: 'Amazon Backend SDE', location: 'Hyderabad', minExperienceYears: 2, salary: 2200000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [1, 18, 32, 7]},
  {id: 67, title: 'Google Frontend Intern', location: 'Bengaluru', minExperienceYears: 0, salary: 800000, employmentType: 'INTERNSHIP', companyId: 6, skillIds: [10, 12, 22]},
  {id: 68, title: 'TCS Full Stack Developer', location: 'Pune', minExperienceYears: 2, salary: 1100000, employmentType: 'FULL_TIME', companyId: 2, skillIds: [1, 10, 12, 18]},
  {id: 69, title: 'Wipro Cloud Consultant', location: 'Delhi', minExperienceYears: 4, salary: 1600000, employmentType: 'FULL_TIME', companyId: 3, skillIds: [9, 34, 7, 23]},
  {id: 70, title: 'Accenture Integration Engineer', location: 'Mumbai', minExperienceYears: 5, salary: 1900000, employmentType: 'FULL_TIME', companyId: 4, skillIds: [1, 5, 33, 17]},
  {id: 71, title: 'Zoho Python Developer', location: 'Chennai', minExperienceYears: 1, salary: 1000000, employmentType: 'FULL_TIME', companyId: 11, skillIds: [14, 37, 18, 3]},
  {id: 72, title: 'Flipkart Search Relevance Engineer', location: 'Bengaluru', minExperienceYears: 6, salary: 3100000, employmentType: 'FULL_TIME', companyId: 8, skillIds: [30, 14, 15, 27]},
  {id: 73, title: 'Contract DevOps Engineer', location: 'Remote', minExperienceYears: 5, salary: 2400000, employmentType: 'CONTRACT', companyId: 16, skillIds: [8, 24, 9, 23, 25]},
  {id: 74, title: 'Junior React Developer', location: 'Mumbai', minExperienceYears: 1, salary: 900000, employmentType: 'FULL_TIME', companyId: 15, skillIds: [10, 12, 18, 22]},
  {id: 75, title: 'Staff Data Platform Engineer', location: 'Bengaluru', minExperienceYears: 8, salary: 3800000, employmentType: 'FULL_TIME', companyId: 5, skillIds: [14, 27, 39, 5, 35]}
] AS row
MERGE (j:Job {id: row.id})
SET j.title = row.title,
    j.location = row.location,
    j.minExperienceYears = row.minExperienceYears,
    j.salary = row.salary,
    j.employmentType = row.employmentType
WITH j, row
MATCH (co:Company {id: row.companyId})
MERGE (j)-[:POSTED_BY]->(co)
WITH j, row
MATCH (loc:Location {name: row.location})
MERGE (j)-[:LOCATED_IN]->(loc)
WITH j, row
UNWIND row.skillIds AS skillId
MATCH (s:Skill {id: skillId})
MERGE (j)-[:REQUIRES_SKILL {required: true}]->(s);
